CREATE TABLE `clanovi` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sifra` varchar(11) DEFAULT NULL,
  `loza` int(11) unsigned NOT NULL,
  `drzava` int(11) unsigned DEFAULT NULL,
  `prezime` varchar(50) NOT NULL DEFAULT '',
  `ime` varchar(50) NOT NULL DEFAULT '',
  `spol` smallint(6) NOT NULL DEFAULT 0,
  `datum_rodjenja` date DEFAULT NULL,
  `oib` char(11) DEFAULT NULL,
  `datum_ulaska_lozu` date DEFAULT NULL COMMENT 'Datum ulaska člana u ovu ložu',
  `datum_izlaska_pokrivanja` date DEFAULT NULL COMMENT 'Datum napuštanja obedijencije ili pokrivanja člana',
  `datum_inicijacije` date DEFAULT NULL,
  `porijeklo` int(11) unsigned DEFAULT NULL,
  `stupanj` int(11) unsigned DEFAULT NULL,
  `datum_stupnja` date DEFAULT NULL,
  `telefon` int(11) unsigned DEFAULT NULL,
  `e_mail` int(11) unsigned DEFAULT NULL,
  `adresa` int(11) unsigned DEFAULT NULL,
  `na_prijedlog` int(11) unsigned DEFAULT NULL,
  `slika` longblob DEFAULT NULL,
  `slika_mime` varchar(32) DEFAULT NULL,
  `slika_thumbnail` mediumblob DEFAULT NULL,
  `slika_thumbnail_mime` varchar(32) DEFAULT NULL,
  `slika_thumb_round` mediumblob DEFAULT NULL,
  `slika_thumb_round_mime` varchar(32) DEFAULT NULL,
  `slika_thumb_round_position` smallint(6) DEFAULT NULL,
  `napomena` varchar(1024) NOT NULL DEFAULT '',
  `upisano` datetime DEFAULT NULL,
  `upisao` int(11) DEFAULT NULL,
  `aktivnost` tinyint(1) NOT NULL DEFAULT 0,
  `kandidat` tinyint(1) NOT NULL DEFAULT 0,
  `zastavice` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_clanovi_drzava_sifra` (`drzava`,`sifra`),
  KEY `ix_clanovi_loza` (`loza`),
  KEY `ix_clanovi_porijeklo` (`porijeklo`),
  KEY `ix_clanovi_stupanj` (`stupanj`),
  KEY `ix_clanovi_telefon` (`telefon`),
  KEY `ix_clanovi_e_mail` (`e_mail`),
  KEY `ix_clanovi_adresa` (`adresa`),
  KEY `ix_clanovi_na_prijedlog` (`na_prijedlog`),
  KEY `ix_clanovi_drzava` (`drzava`),
  CONSTRAINT `fk_clanovi_adrese` FOREIGN KEY (`adresa`) REFERENCES `adrese` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_drzave` FOREIGN KEY (`drzava`) REFERENCES `drzave` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_emaili` FOREIGN KEY (`e_mail`) REFERENCES `e_maili` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_loze` FOREIGN KEY (`loza`) REFERENCES `loze` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_na_prijedlog` FOREIGN KEY (`na_prijedlog`) REFERENCES `clanovi` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_porijeklo` FOREIGN KEY (`porijeklo`) REFERENCES `clanovi_porijeklo` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_stupnjevi` FOREIGN KEY (`stupanj`) REFERENCES `stupnjevi` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_clanovi_telefoni` FOREIGN KEY (`telefon`) REFERENCES `telefoni` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
