-- Obrazac 001a kandidata; jedan zapis po članu (1:1). Popunjava se u app, generira PDF (kandidat potpisuje).
CREATE TABLE `kandidat_dokumenti_001` (
  `id`                 int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_clan`            int(11) unsigned NOT NULL COMMENT 'ID člana (veza na clanovi.id); jedinstven (1 obrazac 001a po članu)',
  `id_loza`            int(11) unsigned DEFAULT NULL COMMENT 'ID lože kandidata (denormalizirano iz clanovi.loza) — most za PDF u jednom skoku',
  `datum_dokumenta`    date DEFAULT NULL COMMENT 'Datum obrasca (upisuje korisnik; ispisuje se na obrascu)',
  `mjesto_rodjenja`    varchar(100) NOT NULL DEFAULT '' COMMENT 'Mjesto rođenja',
  `drzava_rodjenja`    varchar(100) NOT NULL DEFAULT '' COMMENT 'Država rođenja (slobodan tekst)',
  `drzavljanstvo`      varchar(100) NOT NULL DEFAULT '' COMMENT 'Državljanstvo (slobodan tekst)',
  `zvanje`             varchar(100) NOT NULL DEFAULT '' COMMENT 'Zvanje',
  `zanimanje`          varchar(100) NOT NULL DEFAULT '' COMMENT 'Zanimanje',
  `gradjanski_status`  varchar(100) NOT NULL DEFAULT '' COMMENT 'Građanski status (slobodan tekst)',
  `broj_djece`         tinyint(3) unsigned DEFAULT NULL COMMENT 'Broj djece',
  `poznavanje_jezika`  varchar(255) NOT NULL DEFAULT '' COMMENT 'Poznavanje jezika (slobodan tekst)',
  `pocasni_naslovi`    varchar(255) NOT NULL DEFAULT '' COMMENT 'Počasni naslovi',
  `dijete_masona`      tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Je li dijete masona: 0=Ne, 1=Da',
  `veza_masoni`        tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ima li druge poveznice s masonima (obiteljske/rođačke/partnerske/bračne): 0=Ne, 1=Da',
  `zahtjev_druga_loza` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Je li predao zahtjev drugoj Loži ili Masonskoj Obedijenciji: 0=Ne, 1=Da',
  `primljen_iniciran`  enum('Primljen','Iniciran') DEFAULT NULL COMMENT 'Status: Primljen ili Iniciran',
  `dokument_prored`    decimal(3,2) DEFAULT NULL COMMENT 'Korisnički (ekstra) prored u tijelu teksta za PDF',
  `upisao`             int(11) unsigned DEFAULT NULL COMMENT 'ID onoga tko je upisao obrazac',
  `datum_upisa`        datetime DEFAULT NULL COMMENT 'Vrijeme sa servera kada je obrazac upisan',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kd001_clan` (`id_clan`),
  KEY `fk_kd001_loza` (`id_loza`),
  KEY `fk_kd001_upisao` (`upisao`),
  CONSTRAINT `fk_kd001_clan` FOREIGN KEY (`id_clan`) REFERENCES `clanovi` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_loza` FOREIGN KEY (`id_loza`) REFERENCES `loze` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_upisao` FOREIGN KEY (`upisao`) REFERENCES `clanovi` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
