-- Obrazac 001a kandidata; jedan zapis po članu (1:1). Popunjava se u app, generira PDF (kandidat potpisuje).
CREATE TABLE `kandidat_dokumenti_001` (
  `id`                 int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_clan`            int(11) unsigned NOT NULL COMMENT 'ID člana (veza na clanovi.id); jedinstven (1 obrazac 001a po članu)',
  `id_loza`            int(11) unsigned DEFAULT NULL COMMENT 'ID lože kandidata (denormalizirano iz clanovi.loza) — most za PDF u jednom skoku',
  `id_regija`          int(11) unsigned DEFAULT NULL COMMENT 'ID regije kandidata (denormalizirano iz loze.id_regija preko clanovi.loza) — most za PDF u jednom skoku (→ regije.naziv)',
  `id_telefon`         int(11) unsigned DEFAULT NULL COMMENT 'ID telefona kandidata (denormalizirano iz clanovi.telefon) — most za PDF u jednom skoku (→ telefoni.telefon)',
  `id_adresa`          int(11) unsigned DEFAULT NULL COMMENT 'ID adrese kandidata (denormalizirano iz clanovi.adresa) — most za PDF u jednom skoku (→ adrese.*)',
  `id_drzave`          int(11) unsigned DEFAULT NULL COMMENT 'ID države adrese kandidata (denormalizirano iz adrese.id_drzave_adrese) — most za PDF u jednom skoku (→ drzave_adresa.naziv)',
  `id_zivotopis`       int(11) unsigned DEFAULT NULL COMMENT 'Most za PDF: red životopisa kandidata (kandidat_dokumenti_zivotopis.id)',
  `id_ostalo`          int(11) unsigned DEFAULT NULL COMMENT 'Most za PDF: red taba „Ostalo" (kandidat_dokumenti_ostalo.id)',
  `id_loza_pridruzivana` int(11) unsigned DEFAULT NULL COMMENT 'Most za PDF: loža iz koje se kandidat pridružuje (kopija kandidat_dokumenti_ostalo.loza_pridruzivana → loze.id)',
  `datum_dokumenta`    date DEFAULT NULL COMMENT 'Datum obrasca (upisuje korisnik; ispisuje se na obrascu)',
  `mjesto_rodjenja`    varchar(100) NOT NULL DEFAULT '' COMMENT 'Mjesto rođenja',
  `drzava_rodjenja`    varchar(100) NOT NULL DEFAULT '' COMMENT 'Država rođenja (slobodan tekst)',
  `drzavljanstvo`      varchar(100) NOT NULL DEFAULT '' COMMENT 'Državljanstvo (slobodan tekst)',
  `zvanje`             varchar(100) NOT NULL DEFAULT '' COMMENT 'Zvanje',
  `zanimanje`          varchar(100) NOT NULL DEFAULT '' COMMENT 'Zanimanje',
  `gradjanski_status`  varchar(100) NOT NULL DEFAULT '' COMMENT 'Građanski status (slobodan tekst)',
  `broj_djece`         tinyint(3) unsigned DEFAULT NULL COMMENT 'Broj djece',
  `poznavanje_jezika`  varchar(255) NOT NULL DEFAULT '' COMMENT 'Poznavanje jezika (slobodan tekst)',
  `pocasni_naslovi`    varchar(255) NOT NULL DEFAULT '' COMMENT 'Počasni naslovi',
  `dijete_masona`      tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Je li dijete masona: 0=Ne, 1=Da',
  `veza_masoni`        tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ima li druge poveznice s masonima (obiteljske/rođačke/partnerske/bračne): 0=Ne, 1=Da',
  `zahtjev_druga_loza` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Je li predao zahtjev drugoj Loži ili Masonskoj Obedijenciji: 0=Ne, 1=Da',
  `status_pristupa`  enum('Iniciran','Reguliran','Pridružen') DEFAULT NULL COMMENT 'Status pristupa: Iniciran, Reguliran ili Pridružen',
  `predlagaci`         varchar(255) DEFAULT NULL COMMENT 'Obrazac 001b: id-evi članova predlagača (clanovi.id) odvojeni zarezom; NULL ako nijedan',
  `glasanje_1`         varchar(64) DEFAULT NULL COMMENT 'Obrazac 001b: 1. glasanje — "datum,glasača,za,protiv,suzdržani" (datum ISO YYYY-MM-DD ili -1; brojevi ili -1); NULL ako je cijeli stupac prazan',
  `glasanje_2`         varchar(64) DEFAULT NULL COMMENT 'Obrazac 001b: 2. glasanje — isti format kao glasanje_1',
  `glasanje_3`         varchar(64) DEFAULT NULL COMMENT 'Obrazac 001b: 3. glasanje — isti format kao glasanje_1',
  `datum_razmatranja`  date DEFAULT NULL COMMENT 'Obrazac 001b: datum radova razmatranja',
  `datum_odbijanja`    date DEFAULT NULL COMMENT 'Obrazac 001b: datum odbijanja',
  `razlog_odbijanja`   varchar(1024) DEFAULT NULL COMMENT 'Obrazac 001b: razlog odbijanja (slobodan tekst); popunjava se samo ako je datum_odbijanja valjan, inače NULL',
  `casni_id`           int(11) unsigned DEFAULT NULL COMMENT 'Obrazac 001b: ID časnog majstora (clanovi.id)',
  `vip_id`             int(11) unsigned DEFAULT NULL COMMENT 'Obrazac 001b: ID inspektora / VIP (clanovi.id)',
  `dokument_prored`    decimal(3,2) DEFAULT NULL COMMENT 'Korisnički (ekstra) prored u tijelu teksta za PDF',
  `upisao`             int(11) unsigned DEFAULT NULL COMMENT 'ID onoga tko je upisao obrazac',
  `datum_upisa`        datetime DEFAULT NULL COMMENT 'Vrijeme sa servera kada je obrazac upisan',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kd001_clan` (`id_clan`),
  KEY `fk_kd001_loza` (`id_loza`),
  KEY `fk_kd001_regija` (`id_regija`),
  KEY `fk_kd001_telefon` (`id_telefon`),
  KEY `fk_kd001_adresa` (`id_adresa`),
  KEY `fk_kd001_drzave` (`id_drzave`),
  KEY `fk_kd001_zivotopis` (`id_zivotopis`),
  KEY `fk_kd001_ostalo` (`id_ostalo`),
  KEY `fk_kd001_loza_pridruzivana` (`id_loza_pridruzivana`),
  KEY `fk_kd001_upisao` (`upisao`),
  KEY `fk_kd001_casni` (`casni_id`),
  KEY `fk_kd001_vip` (`vip_id`),
  CONSTRAINT `fk_kd001_clan` FOREIGN KEY (`id_clan`) REFERENCES `clanovi` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_casni` FOREIGN KEY (`casni_id`) REFERENCES `clanovi` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_vip` FOREIGN KEY (`vip_id`) REFERENCES `clanovi` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_loza` FOREIGN KEY (`id_loza`) REFERENCES `loze` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_regija` FOREIGN KEY (`id_regija`) REFERENCES `regije` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_telefon` FOREIGN KEY (`id_telefon`) REFERENCES `telefoni` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_adresa` FOREIGN KEY (`id_adresa`) REFERENCES `adrese` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_drzave` FOREIGN KEY (`id_drzave`) REFERENCES `drzave_adresa` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_zivotopis` FOREIGN KEY (`id_zivotopis`) REFERENCES `kandidat_dokumenti_zivotopis` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_ostalo` FOREIGN KEY (`id_ostalo`) REFERENCES `kandidat_dokumenti_ostalo` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_loza_pridruzivana` FOREIGN KEY (`id_loza_pridruzivana`) REFERENCES `loze` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_kd001_upisao` FOREIGN KEY (`upisao`) REFERENCES `clanovi` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
