CREATE TABLE `loze` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_regija` int(11) unsigned NOT NULL,
  `id_obred` int(11) unsigned DEFAULT NULL,
  `id_tip_loze` int(11) DEFAULT NULL,
  `id_drzava` int(11) unsigned DEFAULT NULL,
  `id_drzava_adrese` int(11) unsigned DEFAULT NULL,
  `naziv` varchar(50) DEFAULT NULL,
  `orjent` varchar(250) DEFAULT NULL COMMENT 'Orijent (sjedište) lože — slobodan tekst',
  `adresa_loze_1` varchar(50) NOT NULL DEFAULT '',
  `adresa_loze_2` varchar(50) NOT NULL DEFAULT '',
  `grad` varchar(15) NOT NULL,
  `posta` varchar(6) NOT NULL,
  `telefon_loze` varchar(20) NOT NULL,
  `meil_loze` varchar(30) NOT NULL,
  `datum_nastanka` date DEFAULT NULL,
  `napomena` varchar(1024) NOT NULL DEFAULT '',
  `aktivnost` tinyint(1) NOT NULL DEFAULT 1,
  `slika` longblob DEFAULT NULL,
  `slika_mime` varchar(32) DEFAULT NULL,
  `slika_thumbnail` mediumblob DEFAULT NULL,
  `slika_thumbnail_mime` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_loze_drzava_regija_naziv` (`id_drzava`,`id_regija`,`naziv`),
  KEY `fk_loze_id_tip_loze` (`id_tip_loze`),
  KEY `fk_loze_id_drzava_adrese` (`id_drzava_adrese`),
  KEY `fk_loze_id_drzava` (`id_drzava`),
  KEY `fk_loze_id_obred` (`id_obred`),
  KEY `idx_loze_id_regija` (`id_regija`),
  CONSTRAINT `fk_loze_id_drzava` FOREIGN KEY (`id_drzava`) REFERENCES `drzave` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_loze_id_drzava_adrese` FOREIGN KEY (`id_drzava_adrese`) REFERENCES `drzave_adresa` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_loze_id_obred` FOREIGN KEY (`id_obred`) REFERENCES `obredi` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `loze_ibfk_1` FOREIGN KEY (`id_regija`) REFERENCES `regije` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
