CREATE TABLE `pdf_template` (
  `id`                        int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Jedinstveni ključ templatea',
  `naziv`                     varchar(50) NOT NULL COMMENT 'Naziv templatea',
  `format_papira`             enum('A4','A5','A3','Letter','Legal','custom') NOT NULL DEFAULT 'A4' COMMENT 'Format papira',
  `sirina_mm`                 decimal(6,2) DEFAULT NULL COMMENT 'Širina papira u mm (samo custom)',
  `visina_mm`                 decimal(6,2) DEFAULT NULL COMMENT 'Visina papira u mm (samo custom)',
  `orijentacija`              enum('portrait','landscape') NOT NULL DEFAULT 'portrait' COMMENT 'Orijentacija stranice',
  `margina_gore_mm`           decimal(5,2) NOT NULL DEFAULT 20.00 COMMENT 'Gornja margina u mm',
  `margina_dolje_mm`          decimal(5,2) NOT NULL DEFAULT 20.00 COMMENT 'Donja margina u mm',
  `margina_lijevo_mm`         decimal(5,2) NOT NULL DEFAULT 20.00 COMMENT 'Lijeva margina u mm',
  `margina_desno_mm`          decimal(5,2) NOT NULL DEFAULT 20.00 COMMENT 'Desna margina u mm',
  `zaglavlje`                 tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ima li dokument zaglavlje',
  `zaglavlje_visina_mm`       decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Visina prostora zaglavlja u mm',
  `zaglavlje_padding_mm`      decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Pomak početka tijela ispod zaglavlja u mm',
  `zaglavlje_primjena`        enum('prva','svaka') NOT NULL DEFAULT 'svaka' COMMENT 'Zaglavlje na prvoj ili svakoj stranici',
  `podnozje`                  tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ima li dokument podnožje',
  `podnozje_visina_mm`        decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Visina prostora podnožja u mm',
  `podnozje_padding_mm`       decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Pomak kraja tijela iznad podnožja u mm',
  `podnozje_od_stranice`      smallint(6) NOT NULL DEFAULT 1 COMMENT 'Od koje stranice se podnožje prikazuje',
  `broj_stranice`             tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Prikazuje li se brojač stranica',
  `broj_stranice_format`      varchar(100) NOT NULL DEFAULT 'Stranica #S od #U' COMMENT 'Predložak brojača; #S=trenutna, #U=ukupno',
  `broj_stranice_zona`        enum('podnozje','zaglavlje') NOT NULL DEFAULT 'podnozje' COMMENT 'Zona prikaza brojača',
  `broj_stranice_poravnanje`  enum('lijevo','centar','desno') NOT NULL DEFAULT 'centar' COMMENT 'Poravnanje brojača',
  `naslovna_stranica`         tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ima li dokument naslovnu stranicu',
  `dvostran`                  tinyint(1) NOT NULL DEFAULT 0 COMMENT 'TODO/budućnost: dvostrani ispis (zasad neaktivno)',
  `vezna_margina_mm`          decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'TODO/budućnost: vezna margina (zasad neaktivno)',
  `napomena`                  varchar(1024) DEFAULT NULL COMMENT 'Slobodna bilješka administratora',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
