CREATE TABLE `pdf_paragraf` (
  `id`                       int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Jedinstveni ključ stila paragrafa',
  `naziv`                    varchar(50) NOT NULL COMMENT 'Naziv stila, npr. "Naslov1", "Tijelo"',
  `font_id`                  int(11) unsigned NOT NULL COMMENT 'FK na pdf_fontovi',
  `velicina_pt`              decimal(5,2) NOT NULL DEFAULT 12.00 COMMENT 'Veličina slova u točkama pt',
  `bold`                     tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podebljano',
  `italic`                   tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Kurziv',
  `podcrtano`                tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podcrtano',
  `boja`                     varchar(7) NOT NULL DEFAULT '#000000' COMMENT 'Boja teksta, hex',
  `boja_pozadine`            varchar(7) DEFAULT NULL COMMENT 'Boja pozadine teksta, hex; NULL=bez',
  `pozadina_cijeli_red`      tinyint(1) NOT NULL DEFAULT 0 COMMENT '0=highlight iza teksta; 1=puna traka',
  `traka_padding_lijevo_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding lijevo trake u mm',
  `traka_padding_desno_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding desno trake u mm',
  `traka_padding_gore_mm`    decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding gore trake u mm',
  `traka_padding_dolje_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding dolje trake u mm',
  `poravnanje`               enum('left','right','center','justify') NOT NULL DEFAULT 'left' COMMENT 'Poravnanje teksta',
  `prored`                   decimal(4,2) NOT NULL DEFAULT 1.00 COMMENT 'Množitelj proreda',
  `razmak_prije_mm`          decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Razmak iznad paragrafa u mm',
  `razmak_poslije_mm`        decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Razmak ispod paragrafa u mm',
  `uvlaka_lijevo_mm`         decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Lijeva uvlaka u mm',
  `uvlaka_desno_mm`          decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Desna uvlaka u mm',
  `uvlaka_prvi_red_mm`       decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Uvlaka prvog retka u mm (simulirana)',
  `napomena`                 varchar(1024) DEFAULT NULL COMMENT 'Slobodna bilješka administratora',
  PRIMARY KEY (`id`),
  KEY `fk_paragraf_font` (`font_id`),
  CONSTRAINT `fk_paragraf_font` FOREIGN KEY (`font_id`) REFERENCES `pdf_fontovi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
