CREATE TABLE `pdf_paragraf` (
  `id`                       int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Jedinstveni ključ stila paragrafa',
  `naziv`                    varchar(50) NOT NULL COMMENT 'Naziv stila, npr. "Naslov1", "Tijelo"',
  `font_id`                  int(11) unsigned NOT NULL COMMENT 'FK na pdf_fontovi',
  `velicina_pt`              decimal(5,2) NOT NULL DEFAULT 12.00 COMMENT 'Veličina slova u točkama pt',
  `bold`                     tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podebljano',
  `italic`                   tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Kurziv',
  `podcrtano`                tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podcrtano',
  `boja`                     varchar(7) NOT NULL DEFAULT '#000000' COMMENT 'Boja teksta, hex',
  `boja_pozadine`            varchar(7) DEFAULT NULL COMMENT 'Boja pozadine teksta, hex; NULL=bez',
  `pozadina_cijeli_red`      tinyint(1) NOT NULL DEFAULT 0 COMMENT '0=highlight iza teksta; 1=puna traka',
  `traka_padding_lijevo_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding lijevo trake u mm',
  `traka_padding_desno_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding desno trake u mm',
  `traka_padding_gore_mm`    decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding gore trake u mm',
  `traka_padding_dolje_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding dolje trake u mm',
  `poravnanje`               enum('left','right','center','justify') NOT NULL DEFAULT 'left' COMMENT 'Poravnanje teksta',
  `prored`                   decimal(4,2) NOT NULL DEFAULT 1.00 COMMENT 'Množitelj proreda',
  `razmak_prije_mm`          decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Razmak iznad paragrafa u mm',
  `razmak_poslije_mm`        decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Razmak ispod paragrafa u mm',
  `uvlaka_lijevo_mm`         decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Lijeva uvlaka u mm',
  `uvlaka_desno_mm`          decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Desna uvlaka u mm',
  `uvlaka_prvi_red_mm`       decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Uvlaka prvog retka u mm (simulirana)',
  `okvir_debljina_gore_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina gornje linije okvira u mm; 0=nema linije',
  `okvir_debljina_dolje_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina donje linije okvira u mm; 0=nema linije',
  `okvir_debljina_lijevo_mm` decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina lijeve linije okvira u mm; 0=nema linije',
  `okvir_debljina_desno_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina desne linije okvira u mm; 0=nema linije',
  `okvir_padding_gore_mm`    decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Unutarnji razmak teksta od gornje linije okvira u mm',
  `okvir_padding_dolje_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Unutarnji razmak teksta od donje linije okvira u mm',
  `okvir_padding_lijevo_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Unutarnji razmak teksta od lijeve linije okvira u mm',
  `okvir_padding_desno_mm`   decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Unutarnji razmak teksta od desne linije okvira u mm',
  `okvir_boja`               varchar(7) NOT NULL DEFAULT '#000000' COMMENT 'Boja linija okvira, hex; jedna za sve 4 strane',
  `okvir_boja_podloge`       varchar(7) DEFAULT NULL COMMENT 'Boja podloge (ispune) okvira, hex; NULL=bez ispune. Kad okvir postoji, dominira nad boja_pozadine/traka',
  `okvir_do_lijeve_margine`  tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Lijevi rub okvira ide do lijeve margine (1) ili po sadrzaju teksta (0)',
  `okvir_do_desne_margine`   tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Desni rub okvira ide do desne margine (1) ili po sadrzaju teksta (0)',
  `okvir_postuj_uvlaku`      tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Kad strana ide do margine, a ovo=1, ide do uvlake te strane (uvlaka_lijevo/desno) umjesto do margine; vrijedi za obje strane',
  `napomena`                 varchar(1024) DEFAULT NULL COMMENT 'Slobodna bilješka administratora',
  PRIMARY KEY (`id`),
  KEY `fk_paragraf_font` (`font_id`),
  CONSTRAINT `fk_paragraf_font` FOREIGN KEY (`font_id`) REFERENCES `pdf_fontovi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
