-- =====================================================================
-- Stil tablice — kreiranje tablica (HeidiSQL, ručno). Skeema: db-schema/vnlh/pdf_tablica_stil*.sql
-- Roditelj pa child. Bez seed podataka.
-- =====================================================================

CREATE TABLE `pdf_tablica_stil` (
  `id`                            int(11) unsigned NOT NULL AUTO_INCREMENT,
  `naziv`                         varchar(50) NOT NULL COMMENT 'Naziv stila tablice (jedinstven)',
  `napomena`                      varchar(1024) DEFAULT NULL COMMENT 'Interna napomena administratora',
  `zaglavlje_font_id`             int(11) unsigned DEFAULT NULL COMMENT 'FK pdf_fontovi — font zaglavlja',
  `zaglavlje_velicina_pt`         decimal(5,2) DEFAULT NULL COMMENT 'Veličina fonta zaglavlja (pt)',
  `zaglavlje_bold`                tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Zaglavlje podebljano',
  `zaglavlje_italic`              tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Zaglavlje kurziv',
  `zaglavlje_podcrtano`           tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Zaglavlje podcrtano',
  `zaglavlje_boja`                varchar(7) DEFAULT NULL COMMENT 'Boja teksta zaglavlja (#RRGGBB)',
  `podaci_font_id`                int(11) unsigned DEFAULT NULL COMMENT 'FK pdf_fontovi — font podataka',
  `podaci_velicina_pt`            decimal(5,2) DEFAULT NULL COMMENT 'Veličina fonta podataka (pt)',
  `podaci_bold`                   tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podaci podebljano',
  `podaci_italic`                 tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podaci kurziv',
  `podaci_podcrtano`              tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Podaci podcrtano',
  `podaci_boja`                   varchar(7) DEFAULT NULL COMMENT 'Boja teksta podataka (#RRGGBB)',
  `okvir_debljina_mm`             decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Vanjski okvir tablice (sve 4 strane); 0 = bez',
  `okvir_boja`                    varchar(7) DEFAULT NULL COMMENT 'Boja vanjskog okvira',
  `zaglavlje_linija_debljina_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina linije ISPOD zaglavlja',
  `zaglavlje_linija_boja`         varchar(7) DEFAULT NULL COMMENT 'Boja linije ispod zaglavlja',
  `linija_vert_debljina_mm`       decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina okomitih linija (između stupaca)',
  `linija_vert_boja`              varchar(7) DEFAULT NULL COMMENT 'Boja okomitih linija',
  `linija_red_debljina_mm`        decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Debljina vodoravnih linija između redaka podataka',
  `linija_red_boja`               varchar(7) DEFAULT NULL COMMENT 'Boja linija između redaka',
  `zaglavlje_pozadina`            tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Ima li zaglavlje pozadinu',
  `zaglavlje_pozadina_boja`       varchar(7) DEFAULT NULL COMMENT 'Boja pozadine zaglavlja',
  `zebra`                         tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Naizmjenična pozadina parnih redova',
  `zebra_boja`                    varchar(7) DEFAULT NULL COMMENT 'Boja zebra-pozadine',
  `zaglavlje_padding_gore_mm`     decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Vert. padding ćelije zaglavlja — gore',
  `zaglavlje_padding_dolje_mm`    decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Vert. padding ćelije zaglavlja — dolje',
  `podaci_padding_gore_mm`        decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Vert. padding ćelije podataka — gore',
  `podaci_padding_dolje_mm`       decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Vert. padding ćelije podataka — dolje',
  `razdvajac`                     varchar(8) NOT NULL DEFAULT '|' COMMENT 'Razdvajač vrijednosti reda iz stavke (znak kojeg nema u podacima)',
  `prikazi_zaglavlje`             tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Prikaži red zaglavlja',
  `zaglavlje_ponavljanje`         enum('prva','svaka') NOT NULL DEFAULT 'prva' COMMENT 'Zaglavlje samo na 1. stranici / ponovi na svim (pdfmake headerRows)',
  `ne_lomi_red`                   tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Red ne smije prijeći preko stranice (pdfmake dontBreakRows)',
  `razmak_prije_mm`               decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Razmak iznad tablice',
  `razmak_poslije_mm`             decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Razmak ispod tablice',
  `pozicioniranje`                enum('u_tijeku','apsolutno') NOT NULL DEFAULT 'u_tijeku' COMMENT 'U toku dokumenta / apsolutno (x,y)',
  `poravnanje`                    enum('lijevo','centar','desno') NOT NULL DEFAULT 'lijevo' COMMENT 'Poravnanje tablice kad nije puna širina (u_tijeku)',
  `pozicija_x_mm`                 decimal(6,2) DEFAULT NULL COMMENT 'Apsolutno: x gornjeg-lijevog kuta (mm)',
  `pozicija_y_mm`                 decimal(6,2) DEFAULT NULL COMMENT 'Apsolutno: y gornjeg-lijevog kuta (mm)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tablica_stil_naziv` (`naziv`),
  KEY `fk_tablica_stil_zag_font` (`zaglavlje_font_id`),
  KEY `fk_tablica_stil_pod_font` (`podaci_font_id`),
  CONSTRAINT `fk_tablica_stil_zag_font` FOREIGN KEY (`zaglavlje_font_id`) REFERENCES `pdf_fontovi` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tablica_stil_pod_font` FOREIGN KEY (`podaci_font_id`) REFERENCES `pdf_fontovi` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `pdf_tablica_stil_kolona` (
  `id`                    int(11) unsigned NOT NULL AUTO_INCREMENT,
  `tablica_stil_id`       int(11) unsigned NOT NULL COMMENT 'FK pdf_tablica_stil (stil kojem stupac pripada)',
  `redoslijed`            int(11) NOT NULL DEFAULT 0 COMMENT 'Poredak stupca (lijevo→desno); pozicijsko punjenje iz delimitiranog reda',
  `naziv`                 varchar(50) DEFAULT NULL COMMENT 'Interna oznaka stupca (administrator)',
  `zaglavlje`             varchar(100) DEFAULT NULL COMMENT 'Tekst u redu zaglavlja',
  `sirina_tip`            enum('fiksna','popuni') NOT NULL DEFAULT 'popuni' COMMENT 'Fiksna (sirina_mm) / popuni (pdfmake *)',
  `sirina_mm`             decimal(6,2) DEFAULT NULL COMMENT 'Širina kad sirina_tip=fiksna (mm)',
  `zag_orijentacija`      enum('lijevo','centar','desno') NOT NULL DEFAULT 'lijevo' COMMENT 'Poravnanje ćelije zaglavlja',
  `zag_padding_lijevo_mm` decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding zaglavlja — lijevo',
  `zag_padding_desno_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding zaglavlja — desno',
  `zag_prefix`            varchar(50) DEFAULT NULL COMMENT 'Tekst ispred zaglavlja',
  `zag_sufiks`            varchar(50) DEFAULT NULL COMMENT 'Tekst iza zaglavlja',
  `pod_orijentacija`      enum('lijevo','centar','desno') NOT NULL DEFAULT 'lijevo' COMMENT 'Poravnanje ćelije podataka',
  `pod_padding_lijevo_mm` decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding podataka — lijevo',
  `pod_padding_desno_mm`  decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Padding podataka — desno',
  `pod_prefix`            varchar(50) DEFAULT NULL COMMENT 'Tekst ispred vrijednosti',
  `pod_sufiks`            varchar(50) DEFAULT NULL COMMENT 'Tekst iza vrijednosti',
  PRIMARY KEY (`id`),
  KEY `fk_tablica_kolona_stil` (`tablica_stil_id`),
  KEY `idx_tablica_kolona_red` (`tablica_stil_id`, `redoslijed`),
  CONSTRAINT `fk_tablica_kolona_stil` FOREIGN KEY (`tablica_stil_id`) REFERENCES `pdf_tablica_stil` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
